<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="0" failed="7" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_14.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_14.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_30.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_30.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_42.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_42.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_54.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_54.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_06.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_06.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_17.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_17.png' height='100' width='100'/> </a>]]>
    </line>
    <line>
      <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_40.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_40.png' height='100' width='100'/> </a>]]>
    </line>
  </reporter-output>
  <suite started-at="2018-01-26T14:50:38Z" name="Default suite" finished-at="2018-01-26T14:52:41Z" duration-ms="122891">
    <groups>
    </groups>
    <test started-at="2018-01-26T14:50:38Z" name="Default test" finished-at="2018-01-26T14:52:41Z" duration-ms="122891">
      <class name="com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:20:39Z" name="setup" finished-at="2018-01-26T20:21:04Z" duration-ms="25397" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:04Z" name="verify_login_with_invalid_credentials" data-provider="loginData" finished-at="2018-01-26T20:21:14Z" duration-ms="9368" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestData123@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(TC002_VerifyLoginWithInvalidCredentials.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_with_invalid_credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:14Z" name="afterMethod" finished-at="2018-01-26T20:21:16Z" duration-ms="2438" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify_login_with_invalid_credentials status=FAILURE method=TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_14.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_14.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:16Z" name="setup" finished-at="2018-01-26T20:21:25Z" duration-ms="9385" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:25Z" name="verify_login_with_invalid_credentials" data-provider="loginData" finished-at="2018-01-26T20:21:30Z" duration-ms="4802" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[testqa1@yopmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Password@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin/]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(TC002_VerifyLoginWithInvalidCredentials.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_with_invalid_credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:30Z" name="afterMethod" finished-at="2018-01-26T20:21:31Z" duration-ms="1126" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify_login_with_invalid_credentials status=FAILURE method=TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_30.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_30.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:31Z" name="setup" finished-at="2018-01-26T20:21:41Z" duration-ms="9806" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:41Z" name="verify_login_with_invalid_credentials" data-provider="loginData" finished-at="2018-01-26T20:21:42Z" duration-ms="1039" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(TC002_VerifyLoginWithInvalidCredentials.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_with_invalid_credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:42Z" name="afterMethod" finished-at="2018-01-26T20:21:44Z" duration-ms="1273" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify_login_with_invalid_credentials status=FAILURE method=TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_42.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_42.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:44Z" name="setup" finished-at="2018-01-26T20:21:53Z" duration-ms="9494" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:53Z" name="verify_login_with_invalid_credentials" data-provider="loginData" finished-at="2018-01-26T20:21:54Z" duration-ms="1001" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[holly@yopmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(TC002_VerifyLoginWithInvalidCredentials.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_with_invalid_credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:54Z" name="afterMethod" finished-at="2018-01-26T20:21:55Z" duration-ms="951" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify_login_with_invalid_credentials status=FAILURE method=TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_54.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_21_54.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:21:55Z" name="setup" finished-at="2018-01-26T20:22:05Z" duration-ms="9761" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:22:05Z" name="verify_login_with_invalid_credentials" data-provider="loginData" finished-at="2018-01-26T20:22:06Z" duration-ms="979" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123457]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(TC002_VerifyLoginWithInvalidCredentials.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_with_invalid_credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:22:06Z" name="afterMethod" finished-at="2018-01-26T20:22:07Z" duration-ms="1139" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify_login_with_invalid_credentials status=FAILURE method=TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_06.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_06.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:22:07Z" name="setup" finished-at="2018-01-26T20:22:16Z" duration-ms="9448" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:22:16Z" name="verify_login_with_invalid_credentials" data-provider="loginData" finished-at="2018-01-26T20:22:17Z" duration-ms="1020" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[holla@yopmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(TC002_VerifyLoginWithInvalidCredentials.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_with_invalid_credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:22:17Z" name="afterMethod" finished-at="2018-01-26T20:22:18Z" duration-ms="1118" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify_login_with_invalid_credentials status=FAILURE method=TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_17.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_17.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:22:18Z" name="setup" finished-at="2018-01-26T20:22:28Z" duration-ms="9770" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:22:28Z" name="verify_login_with_invalid_credentials" data-provider="loginData" finished-at="2018-01-26T20:22:40Z" duration-ms="12193" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[vikashgupta1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[T3st@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin/DashBoard/Index]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://education-psychiatry-qc.astutetech.com/Admin/Account/Login] but found [http://education-psychiatry-qc.astutetech.com/Admin/DashBoard/Index]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(TC002_VerifyLoginWithInvalidCredentials.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_login_with_invalid_credentials -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa]" started-at="2018-01-26T20:22:40Z" name="afterMethod" finished-at="2018-01-26T20:22:41Z" duration-ms="775" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verify_login_with_invalid_credentials status=FAILURE method=TC002_VerifyLoginWithInvalidCredentials.verify_login_with_invalid_credentials(java.lang.String, java.lang.String)[pri:0, instance:com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials@71e693fa] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_40.png'> <img src='C:\Users\Vikash Gupta\git\APA2\APAsrc\main\java\com\APA\screenShotsverify_login_with_invalid_credentials_26_01_2018_08_22_40.png' height='100' width='100'/> </a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.APA.HomePage.TC002_VerifyLoginWithInvalidCredentials -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
